const DATA = {
	work: [
		{
			logo: "atomic.png",
			company: "Atomic Finance",
			href: "https://atomic.finance",
			role: "Bitcoin Protocol Engineer",
			start: "May 2021",
			end: "Oct 2022",
		},
		{
			logo: "shopify.svg",
			company: "Shopify",
			href: "https://shopify.com",
			role: "Software Engineer",
			start: "January 2021",
			end: "April 2021",
		},
		{
			logo: "nvidia.png",
			company: "Nvidia",
			href: "https://nvidia.com",
			role: "Software Engineer",
			start: "January 2020",
			end: "April 2020",
		},
		{
			logo: "splunk.svg",
			company: "Splunk",
			href: "https://splunk.com",
			role: "Software Engineer",
			start: "January 2019",
			end: "April 2019",
		},
		{
			logo: "lime.svg",
			company: "Lime",
			href: "https://li.me",
			role: "Software Engineer",
			start: "January 2018",
			end: "April 2018",
		},
		{
			logo: "mitremedia.png",
			company: "Mitre Media",
			href: "https://mitremedia.com",
			role: "Software Engineer",
			start: "May 2017",
			end: "August 2017",
		},
	],
	education: [
		{
			logo: "buildspace.jpg",
			company: "Buildspace",
			href: "https://buildspace.so/",
			role: "s3, s4, sf1, s5",
			start: "2023",
			end: "2024",
		},
		{
			logo: "waterloo.png",
			company: "University of Waterloo",
			href: "https://uwaterloo.ca/",
			role: "Bachelor's Degree of Computer Science (BCS)",
			start: "2016",
			end: "2021",
		},
		{
			logo: "laurier.png",
			company: "Wilfrid Laurier University",
			href: "https://wlu.ca/",
			role: "Bachelor's Degree of Business Administration (BBA)",
			start: "2016",
			end: "2021",
		},
		{
			logo: "ib.png",
			company: "International Baccalaureate",
			href: "https://ibo.org/",
			role: "IB Diploma",
			start: "2012",
			end: "2016",
		},
	],
	skills: [
		"React",
		"Next.js",
		"Typescript",
		"Node.js",
		"Python",
		"Go",
		"Postgres",
		"Docker",
		"Kubernetes",
		"Java",
		"C++",
	],
	projects: [
		{
			title: "Chat Collect",
			dates: "Jan 2024 - Feb 2024",
			video: "chat-collect.mp4",
			desc: 'With the release of the <a href="https://openai.com/blog/introducing-the-gpt-store">OpenAI GPT Store</a>, I decided to build a SaaS which allows users to collect email addresses from their GPT users. This is a great way to build an audience and monetize your GPT API usage.',
			tags: [
				"Next.js",
				"Typescript",
				"PostgreSQL",
				"Prisma",
				"TailwindCSS",
				"Stripe",
				"Shadcn UI",
				"Magic UI",
			],
			links: [{ type: "Website", href: "https://chatcollect.com/" }],
		},
		{
			title: "Magic UI",
			dates: "June 2023 - Present",
			video: "magicui.mp4",
			desc: "Designed, developed and sold animated UI components for developers.",
			tags: [
				"Next.js",
				"Typescript",
				"PostgreSQL",
				"Prisma",
				"TailwindCSS",
				"Stripe",
				"Shadcn UI",
				"Magic UI",
			],
			links: [
				{ type: "Website", href: "https://magicui.design/" },
				{ type: "Source", href: "https://github.com/magicuidesign/magicui" },
			],
		},
		{
			title: "llm.report",
			dates: "April 2023 - September 2023",
			video: "llm-report.mp4",
			desc: "Developed an open-source logging and analytics platform for OpenAI: Log your ChatGPT API requests, analyze costs, and improve your prompts.",
			tags: [
				"Next.js",
				"Typescript",
				"PostgreSQL",
				"Prisma",
				"TailwindCSS",
				"Shadcn UI",
				"Magic UI",
				"Stripe",
				"Cloudflare Workers",
			],
			links: [
				{ type: "Website", href: "https://llm.report/" },
				{ type: "Source", href: "https://github.com/dillionverma/llm.report" },
			],
		},
		{
			title: "Automatic Chat",
			dates: "April 2023 - March 2024",
			video: "automatic-chat.mp4",
			desc: "Developed an AI Customer Support Chatbot which automatically responds to customer support tickets using the latest GPT models.",
			tags: [
				"Next.js",
				"Typescript",
				"PostgreSQL",
				"Prisma",
				"TailwindCSS",
				"Shadcn UI",
				"Magic UI",
				"Stripe",
				"Cloudflare Workers",
			],
			links: [{ type: "Website", href: "https://automatic.chat/" }],
		},
	],
	hackathons: [
		{
			date: "November 23rd - 25th, 2018",
			title: "Hack Western 5",
			location: "London, Ontario",
			img: "hack-western.png",
			desc: "Developed a mobile application which delivered bedtime stories to children using augmented reality.",
		},
		{
			date: "September 14th - 16th, 2018",
			title: "Hack The North",
			location: "Waterloo, Ontario",
			img: "hack-the-north.png",
			desc: "Developed a mobile application which delivers university campus wide events in real time to all students.",
		},
		{
			date: "March 23rd - 24th, 2018",
			title: "FirstNet Public Safety Hackathon",
			location: "San Francisco, California",
			img: "firstnet.png",
			desc: "Developed a mobile application which communcicates a victims medical data from inside an ambulance to doctors at hospital.",
		},
		{
			date: "February 3rd - 4th, 2018",
			title: "DeveloperWeek Hackathon",
			location: "San Francisco, California",
			img: "developer-week.jpg",
			desc: "Developed a web application which aggregates social media data regarding cryptocurrencies and predicts future prices.",
			links: [
				{
					type: "GitHub",
					href: "https://github.com/cryptotrends/cryptotrends",
				},
			],
		},
		{
			date: "January 20th - 21st, 2018",
			title: "HackDavis",
			location: "Davis, California",
			img: "hack-davis.png",
			desc: "Developed a mobile application which allocates a daily carbon emission allowance to users to move towards a sustainable environment.",
			links: [
				{ type: "Devpost", href: "https://devpost.com/software/my6footprint" },
				{
					type: "ML",
					href: "https://github.com/Wallet6/my6footprint-machine-learning",
				},
				{ type: "iOS", href: "https://github.com/Wallet6/CarbonWallet" },
				{ type: "Server", href: "https://github.com/Wallet6/wallet6-server" },
			],
		},
		{
			date: "October 13th - 15th, 2017",
			title: "ETH Waterloo",
			location: "Waterloo, Ontario",
			img: "eth-waterloo.png",
			desc: "Developed a blockchain application for doctors and pharmacists to perform trustless transactions and prevent overdosage in patients.",
			links: [{ type: "Organization", href: "https://github.com/ethdocnet" }],
		},
		{
			date: "September 15th - 17th, 2017",
			title: "Hack The North",
			location: "Waterloo, Ontario",
			img: "hack-the-north.png",
			desc: "Developed a virtual reality application allowing users to see themselves in third person.",
			links: [
				{
					type: "Streamer Source",
					href: "https://github.com/justinmichaud/htn2017",
				},
				{
					type: "Client Source",
					href: "https://github.com/dillionverma/RTSPClient",
				},
			],
		},
		{
			date: "August 26th - 27th, 2017",
			title: "Hack The 6ix",
			location: "Toronto, Ontario",
			img: "hack-the-6ix.jpg",
			desc: "Developed an open platform for people shipping items to same place to combine shipping costs and save money.",
			links: [
				{ type: "Source", href: "https://github.com/ShareShip/ShareShip" },
				{ type: "Site", href: "https://share-ship.herokuapp.com/" },
			],
		},
		{
			date: "July 23rd, 2017",
			title: "Stupid Hack Toronto",
			location: "Toronto, Ontario",
			img: "stupid-hackathon.png",
			desc: "Developed a chrome extension which tracks which facebook profiles you have visited and immediately texts your girlfriend if you visited another girls page.",
			links: [
				{
					type: "Source",
					href: "https://github.com/nsagirlfriend/nsagirlfriend",
				},
			],
		},
		{
			date: "June 23rd - 25th, 2017",
			title: "Global AI Hackathon - Toronto",
			location: "Toronto, Ontario",
			img: "global-ai-hackathon.jpg",
			desc: "Developed a python library which can be imported to any python game and change difficulty of the game based on real time emotion of player. This project recieved 1st place prize at the Global AI Hackathon - Toronto and was also invited to demo at NextAI Canada.",
			links: [
				{
					type: "Article",
					href: "https://syncedreview.com/2017/06/26/global-ai-hackathon-in-toronto/",
				},
				{
					type: "Source",
					href: "https://github.com/TinySamosas/",
				},
			],
		},
		{
			date: "June 17th - 18th, 2017",
			title: "McGill AI for Social Innovation Hackathon",
			location: "Montreal, Quebec",
			img: "ai-for-social-good.jpg",
			desc: "Developed realtime facial microexpression analyzer using AI",
		},
		{
			date: "June 10th, 2017",
			title: "Open Source Circular Economy Days Hackathon",
			location: "Toronto, Ontario",
			img: "open-source-circular-economy-days.jpg",
			desc: "Developed a custom admin interface for food waste startup Genecis to manage their data and provide analytics.",
			links: [
				{ type: "Source", href: "https://github.com/dillionverma/genecis" },
			],
		},
		{
			date: "May 19th - 21st, 2017",
			title: "Make School's Student App Competition 2017",
			location: "International",
			img: "make-school-hackathon.png",
			desc: "Improved PocketDoc and submitted to online competition",
			links: [
				{
					type: "Medium Article",
					href: "https://medium.com/make-school/the-winners-of-make-schools-student-app-competition-2017-a6b0e72f190a",
				},
				{
					type: "Devpost",
					href: "https://devpost.com/software/pocketdoc-react-native",
				},
				{
					type: "YouTube",
					href: "https://www.youtube.com/watch?v=XwFdn5Rmx68",
				},
				{
					type: "Source",
					href: "https://github.com/dillionverma/pocketdoc-react-native",
				},
			],
		},
		{
			date: "May 12th - 14th, 2017",
			title: "HackMining",
			location: "Toronto, Ontario",
			img: "hack-mining.png",
			desc: "Developed neural network to optimize a mining process",
		},
		{
			date: "May 5th - 7th, 2017",
			title: "Waterloo Equithon",
			location: "Waterloo, Ontario",
			img: "waterloo-equithon.png",
			desc: "Developed Pocketdoc, an app in which you take a picture of a physical wound, and the app returns common solutions or cures to the injuries or diseases.",
			links: [
				{
					type: "Devpost",
					href: "https://devpost.com/software/pocketdoc-react-native",
				},
				{
					type: "YouTube",
					href: "https://www.youtube.com/watch?v=XwFdn5Rmx68",
				},
				{
					type: "Source",
					href: "https://github.com/dillionverma/pocketdoc-react-native",
				},
			],
		},
		{
			date: "April 28th - 30th, 2017",
			title: "SpaceApps Waterloo",
			location: "Waterloo, Ontario",
			img: "space-apps.png",
			desc: "Developed Earthwatch, a web application which allows users in a plane to virtually see important points of interest about the world below them.",
			links: [
				{ type: "Source", href: "https://github.com/dillionverma/earthwatch" },
			],
		},
		{
			date: "March 24th - 26th, 2017",
			title: "MHacks 9",
			location: "Ann Arbor, Michigan",
			img: "mhacks-9.png",
			desc: "Developed Super Graphic Air Traffic, a VR website made to introduce people to the world of air traffic controlling. This project was built completely using THREE.js as well as a node backend server.",
			links: [
				{
					type: "Source",
					href: "https://github.com/dillionverma/threejs-planes",
				},
			],
		},
		{
			date: "March 4th - 5th, 2017",
			title: "StartHacks I",
			location: "Waterloo, Ontario",
			img: "starthacks.png",
			desc: "Developed at StartHacks 2017, Recipic is a mobile app which allows you to take pictures of ingredients around your house, and it will recognize those ingredients using ClarifAI image recognition API and return possible recipes to make. Recipic recieved 1st place at the hackathon for best pitch and hack.",
			links: [
				{
					type: "Source (Mobile)",
					href: "https://github.com/mattBlackDesign/recipic-ionic",
				},
				{
					type: "Source (Server)",
					href: "https://github.com/mattBlackDesign/recipic-rails",
				},
			],
		},
		{
			date: "February 3rd - 5th, 2017",
			title: "QHacks II",
			location: "Kingston, Ontario",
			img: "qhacks.png",
			desc: "Developed a mobile game which enables city-wide manhunt with random lobbies",
			links: [
				{
					type: "Source (Mobile)",
					href: "https://github.com/dillionverma/human-huntr-react-native",
				},
				{
					type: "Source (API)",
					href: "https://github.com/mattBlackDesign/human-huntr-rails",
				},
			],
		},
		{
			date: "November 26th, 2016",
			title: "Terrible Hacks V",
			location: "Waterloo, Ontario",
			img: "terrible-hacks-v.png",
			desc: "Developed a mock of Windows 11 with interesting notifications and functionality",
			links: [
				{
					type: "Source",
					href: "https://github.com/justinmichaud/TerribleHacks2016-Windows11",
				},
			],
		},
		{
			date: "October 29, 2016",
			title: "Portal Hackathon",
			location: "Kingston, Ontario",
			img: "portal-hackathon.png",
			desc: "Developed an internal widget for uploading assignments using Waterloo's portal app",
			links: [
				{ type: "Source", href: "https://github.com/UWPortalSDK/crowmark" },
			],
		},
	],
};
